"""Add Shopify fields to Store model

Revision ID: fdbf66382f3b
Revises: 
Create Date: 2025-04-16 18:57:59.267734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbf66382f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('shopify_store_id', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('api_version', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('webhook_secret', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('scopes', sa.String(length=500), nullable=True))
    op.add_column('stores', sa.Column('installation_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'installation_complete')
    op.drop_column('stores', 'scopes')
    op.drop_column('stores', 'webhook_secret')
    op.drop_column('stores', 'api_version')
    op.drop_column('stores', 'shopify_store_id')
    # ### end Alembic commands ###
